// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcpwkf4rQI4KGNvnfaPwoSSk268K6HmgQ',
    appId: '1:5007727410:android:64492ee148ec9e47a9152b',
    messagingSenderId: '5007727410',
    projectId: 'steps2-89ed1',
    storageBucket: 'steps2-89ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACblNVQbXMJAQMMtZHaDGL3fgyp-Qn1gE',
    appId: '1:5007727410:ios:75c3bb8c524fbe9aa9152b',
    messagingSenderId: '5007727410',
    projectId: 'steps2-89ed1',
    storageBucket: 'steps2-89ed1.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnneP9_C7HWZMRDd6-e_jVR9fKn4f5UOo',
    appId: '1:5007727410:web:cf63dae2072a2aaba9152b',
    messagingSenderId: '5007727410',
    projectId: 'steps2-89ed1',
    authDomain: 'steps2-89ed1.firebaseapp.com',
    storageBucket: 'steps2-89ed1.appspot.com',
    measurementId: 'G-2FXZQ1H4XW',
  );

}